<#
    .SYNOPSIS
        Build task that corrects JSON schema property types in the DSC v3 adapted
        resource manifests generated by DscResource.Authoring.

    .DESCRIPTION
        DscResource.Authoring's New-DscAdaptedResourceManifest derives each property's
        JSON schema type from the PowerShell AST's TypeName.Name. For a fully-qualified
        type annotation (e.g. [System.Boolean], [System.Int32] - the convention used
        throughout this module's resource classes), AST returns the full dotted name
        ("System.Boolean") rather than the short alias ("bool") the tool's internal
        type-mapping switch expects, so the property silently falls back to "string".
        This is masked for [System.String] properties only because "string" happens
        to be that same fallback default.

        This task re-derives the correct JSON schema type for every property directly
        from the built module's class definitions (walking the inheritance chain, so
        properties declared on AzDevOpsDscResourceBase are covered too) and patches
        both the individual *.dsc.adaptedResource.json files and the combined
        *.dsc.manifests.json list produced by the DscResource.Authoring build tasks.

        Must run after Create_DscAdaptedResourceManifests and
        Create_DscResourceManifestsList, since the latter regenerates its own copies
        of the manifests rather than reading the already-written files.
#>
param
(
    [Parameter()]
    [System.String]
    $ProjectName = (property ProjectName ''),

    [Parameter()]
    [System.String]
    $BuiltModuleBase = (property BuiltModuleBase '')
)

task Fix_DscAdaptedResourceManifestTypes {
    . Set-SamplerTaskVariable

    # Short PowerShell type-name (last dotted segment, lowercased) -> correct JSON Schema type.
    # Only types that DscResource.Authoring's own switch would otherwise mismap need listing here;
    # 'string' isn't included because it's already the tool's fallback default.
    $typeMap = @{
        'boolean' = 'boolean'
        'bool'    = 'boolean'
        'int16'   = 'integer'
        'int32'   = 'integer'
        'int64'   = 'integer'
        'uint16'  = 'integer'
        'uint32'  = 'integer'
        'uint64'  = 'integer'
        'byte'    = 'integer'
        'sbyte'   = 'integer'
        'single'  = 'number'
        'double'  = 'number'
        'decimal' = 'number'
        'float'   = 'number'
    }

    $builtModulePsm1 = Join-Path -Path $BuiltModuleBase -ChildPath "$ProjectName.psm1"

    if (-not (Test-Path -LiteralPath $builtModulePsm1))
    {
        Write-Build -Color 'Yellow' -Text "`tBuilt module script '$builtModulePsm1' not found. Skipping."
        return
    }

    [System.Management.Automation.Language.Token[]] $tokens = $null
    [System.Management.Automation.Language.ParseError[]] $parseErrors = $null
    $moduleAst = [System.Management.Automation.Language.Parser]::ParseFile($builtModulePsm1, [ref] $tokens, [ref] $parseErrors)

    $classAsts = $moduleAst.FindAll(
        { $args[0] -is [System.Management.Automation.Language.TypeDefinitionAst] -and $args[0].IsClass },
        $true
    )

    $classByName = @{}
    foreach ($classAst in $classAsts)
    {
        $classByName[$classAst.Name] = $classAst
    }

    function Resolve-DscPropertyJsonType
    {
        param (
            [System.Management.Automation.Language.TypeDefinitionAst] $ClassAst,
            [string] $PropertyName
        )

        $current = $ClassAst
        while ($null -ne $current)
        {
            $propertyAst = $current.Members |
                Where-Object { $_ -is [System.Management.Automation.Language.PropertyMemberAst] -and $_.Name -eq $PropertyName } |
                Select-Object -First 1

            if ($propertyAst -and $propertyAst.PropertyType)
            {
                $rawTypeName = $propertyAst.PropertyType.TypeName.Name
                $shortTypeName = ($rawTypeName.TrimEnd('[', ']') -split '\.')[-1].ToLowerInvariant()
                return $typeMap[$shortTypeName]
            }

            $baseTypeName = $current.BaseTypes | Select-Object -First 1 -ExpandProperty TypeName | Select-Object -ExpandProperty Name -ErrorAction SilentlyContinue
            $current = if ($baseTypeName -and $classByName.ContainsKey($baseTypeName)) { $classByName[$baseTypeName] } else { $null }
        }

        return $null
    }

    function Update-ManifestSchemaTypes
    {
        param ($Manifest)

        $resourceShortName = ($Manifest.type -split '/')[-1]

        if (-not $classByName.ContainsKey($resourceShortName))
        {
            return $false
        }

        $classAst = $classByName[$resourceShortName]
        $properties = $Manifest.schema.embedded.properties
        $changed = $false

        if ($null -eq $properties)
        {
            return $false
        }

        foreach ($propName in @($properties.PSObject.Properties.Name))
        {
            $correctType = Resolve-DscPropertyJsonType -ClassAst $classAst -PropertyName $propName

            if ($null -ne $correctType -and $properties.$propName.type -ne $correctType)
            {
                $properties.$propName.type = $correctType
                $changed = $true
            }
        }

        return $changed
    }

    $fixedResourceCount = 0

    Get-ChildItem -Path $BuiltModuleBase -Filter '*.dsc.adaptedResource.json' | ForEach-Object {
        $manifest = Get-Content -Raw -LiteralPath $_.FullName | ConvertFrom-Json

        if (Update-ManifestSchemaTypes -Manifest $manifest)
        {
            $fixedResourceCount++
            Write-Build -Color 'DarkGray' -Text "`tCorrected property types in '$($_.Name)'."
            $manifest | ConvertTo-Json -Depth 20 | Set-Content -LiteralPath $_.FullName -Encoding 'UTF8' -Force
        }
    }

    $listPath = Join-Path -Path $BuiltModuleBase -ChildPath "$ProjectName.dsc.manifests.json"

    if (Test-Path -LiteralPath $listPath)
    {
        $list = Get-Content -Raw -LiteralPath $listPath | ConvertFrom-Json
        $listChanged = $false

        foreach ($manifest in $list.adaptedResources)
        {
            if (Update-ManifestSchemaTypes -Manifest $manifest)
            {
                $listChanged = $true
            }
        }

        if ($listChanged)
        {
            Write-Build -Color 'DarkGray' -Text "`tCorrected property types in '$($listPath | Split-Path -Leaf)'."
            $list | ConvertTo-Json -Depth 20 | Set-Content -LiteralPath $listPath -Encoding 'UTF8' -Force
        }
    }

    if ($fixedResourceCount -eq 0)
    {
        Write-Build -Color 'DarkGray' -Text "`tNo property type corrections needed."
    }
    else
    {
        Write-Build -Color 'Green' -Text "`tCorrected property types for $fixedResourceCount resource manifest(s)."
    }
}
